version: "3.9"

services:
  mongo:
    image: mongo:6
    container_name: eduverse-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: eduverse

  api:
    build:
      context: ./server
    container_name: eduverse-api
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      NODE_ENV: production
      PORT: 4000
      MONGO_URI: mongodb://mongo:27017/eduverse
      CORS_ORIGIN: http://localhost:8080
    depends_on:
      - mongo
    ports:
      - "4000:4000"

  web:
    build:
      context: ./client
    container_name: eduverse-web
    restart: unless-stopped
    environment:
      - VITE_API_BASE_URL=http://localhost:4000
    depends_on:
      - api
    ports:
      - "8080:80"

volumes:
  mongo_data:
